defmodule BotArmyLibraryRuntime.ConfigLoader do
  @moduledoc """
  Load bot configuration from a pre-generated config file (deployed by Salt)
  instead of relying on environment variables.

  This avoids the macOS launchd environment variable pass-through limitation
  where System.get_env() returns nil for wrapper-sourced variables.

  Salt generates `/etc/bot_army/<BOT_NAME>.config.exs` at deployment time with
  all configuration values. This module reads that file at boot and provides
  functions to access values.

  Fallback: If the config file doesn't exist, falls back to System.get_env()
  for backward compatibility during development.
  """

  require Logger

  @doc """
  Load configuration from file generated by Salt deployment.

  Returns a map of configuration values, or an empty map if file not found.
  """
  def load_config do
    config_file = config_file_path()

    if File.exists?(config_file) do
      Logger.info("[ConfigLoader] Loading config from #{config_file}")

      case load_file(config_file) do
        {:ok, config} ->
          Logger.info(
            "[ConfigLoader] Loaded #{map_size(config)} config values from #{config_file}"
          )

          config

        {:error, reason} ->
          Logger.warning(
            "[ConfigLoader] Failed to load #{config_file}: #{inspect(reason)}, falling back to env vars"
          )

          %{}
      end
    else
      Logger.debug(
        "[ConfigLoader] Config file not found at #{config_file}, using env vars (development mode)"
      )

      %{}
    end
  end

  @doc """
  Get a configuration value by key, with optional fallback to environment variable.

  Uses precedence:
  1. Value from config file (if loaded)
  2. Environment variable (fallback)
  3. Default value (if provided)

  Example:
    ConfigLoader.get("COMPANION_NODE_ROLE", "primary")  # fallback to env var, then default
    ConfigLoader.get("COMPANION_NODE_ROLE", fn -> "primary" end)  # using function
  """
  def get(key, default \\ nil) when is_binary(key) do
    config = Application.get_env(:bot_army_library_runtime, :config_data, %{})

    # Try config file first
    case Map.get(config, key) do
      nil ->
        # Fall back to environment variable
        case System.get_env(key) do
          nil ->
            # Use default
            case default do
              func when is_function(func, 0) -> func.()
              _ -> default
            end

          env_value ->
            env_value
        end

      value ->
        value
    end
  end

  @doc """
  Parse an env var value as :primary or :standby role.
  Defaults to :primary if not set or unrecognized.
  """
  def get_role(env_var_name) when is_binary(env_var_name) do
    case get(env_var_name, :primary) do
      "standby" -> :standby
      "primary" -> :primary
      :standby -> :standby
      :primary -> :primary
      _ -> :primary
    end
  end

  # ─────────────────────────────────────────────────────────────

  defp config_file_path do
    app_name = app_name_from_env()
    "/etc/bot_army/#{app_name}.config.exs"
  end

  defp app_name_from_env do
    # Try common bot environment variable names
    System.get_env("RELEASE_NAME") ||
      System.get_env("APP_NAME") ||
      System.get_env("BOT_NAME") ||
      "bot_army"
  end

  defp load_file(path) do
    case File.read(path) do
      {:ok, content} ->
        # Parse Elixir config file format
        try do
          # Use Code.eval_string carefully - config file should only contain a map literal
          {config, _bindings} = Code.eval_string(content, [])
          {:ok, config}
        rescue
          e ->
            {:error, "Failed to parse config file: #{inspect(e)}"}
        end

      {:error, reason} ->
        {:error, reason}
    end
  end
end
