defmodule BotArmyLibraryRuntime.ConfigLoader do
  @moduledoc """
  Load bot configuration from a pre-generated config file (deployed by Salt)
  instead of relying on environment variables.

  This avoids the macOS launchd environment variable pass-through limitation
  where System.get_env() returns nil for wrapper-sourced variables.

  Salt generates `/etc/bot_army/<BOT_NAME>.config.exs` at deployment time with
  all configuration values. This module reads that file at boot and provides
  functions to access values.

  Fallback: If the config file doesn't exist, falls back to System.get_env()
  for backward compatibility during development.
  """

  require Logger

  @doc """
  Load configuration from file generated by Salt deployment.

  Returns a map of configuration values, or an empty map if file not found.
  """
  def load_config do
    config_file = config_file_path()
    write_debug("[ConfigLoader] Attempting to load config from: #{config_file}")

    if File.exists?(config_file) do
      Logger.info("[ConfigLoader] Loading config from #{config_file}")
      write_debug("[ConfigLoader] File exists, attempting to parse...")

      case load_file(config_file) do
        {:ok, config} ->
          count = if is_map(config), do: map_size(config), else: 0

          Logger.info("[ConfigLoader] Loaded #{count} config values from #{config_file}")

          write_debug("[ConfigLoader] ✓ Successfully loaded #{count} values")
          config

        {:error, reason} ->
          Logger.warning(
            "[ConfigLoader] Failed to load #{config_file}: #{inspect(reason)}, falling back to env vars"
          )

          write_debug("[ConfigLoader] ✗ Failed to parse: #{inspect(reason)}")
          %{}
      end
    else
      Logger.debug(
        "[ConfigLoader] Config file not found at #{config_file}, using env vars (development mode)"
      )

      write_debug("[ConfigLoader] Config file NOT FOUND at #{config_file}")
      %{}
    end
  end

  @doc """
  Get a configuration value by key, with optional fallback to environment variable.

  Uses precedence:
  1. Value from config file (if loaded)
  2. Environment variable (fallback)
  3. Default value (if provided)

  Example:
    ConfigLoader.get("COMPANION_NODE_ROLE", "primary")  # fallback to env var, then default
    ConfigLoader.get("COMPANION_NODE_ROLE", fn -> "primary" end)  # using function
  """
  def get(key, default \\ nil) when is_binary(key) do
    config = Application.get_env(:bot_army_library_runtime, :config_data, %{})

    # Try config file first
    case Map.get(config, key) do
      nil ->
        # Fall back to environment variable
        case System.get_env(key) do
          nil ->
            # Use default
            case default do
              func when is_function(func, 0) -> func.()
              _ -> default
            end

          env_value ->
            env_value
        end

      value ->
        value
    end
  end

  @doc """
  Parse an env var value as :primary or :standby role.
  Defaults to :primary if not set or unrecognized.
  """
  def get_role(env_var_name) when is_binary(env_var_name) do
    case get(env_var_name, :primary) do
      "standby" -> :standby
      "primary" -> :primary
      :standby -> :standby
      :primary -> :primary
      _ -> :primary
    end
  end

  # ─────────────────────────────────────────────────────────────

  defp write_debug(msg) do
    # Write to a file we can read later for debugging
    debug_file = "/tmp/configloader-debug.log"

    try do
      File.write(debug_file, msg <> "\n", [:append])
    rescue
      _ -> :ok
    end

    # Also try Logger
    Logger.debug(msg)
  end

  defp config_file_path do
    app_name = app_name_from_env()
    "/etc/bot_army/#{app_name}.config.exs"
  end

  defp app_name_from_env do
    # Try common bot environment variable names
    System.get_env("RELEASE_NAME") ||
      System.get_env("APP_NAME") ||
      System.get_env("BOT_NAME") ||
      "bot_army"
  end

  defp load_file(path) do
    case File.read(path) do
      {:ok, content} ->
        write_debug("[ConfigLoader] Read #{byte_size(content)} bytes from #{path}")

        # Parse Elixir config file format
        try do
          # Use Code.eval_string carefully - config file should only contain a map literal
          write_debug("[ConfigLoader] Parsing Elixir code with Code.eval_string...")
          {config, _bindings} = Code.eval_string(content, [])

          case config do
            m when is_map(m) ->
              write_debug("[ConfigLoader] ✓ Parsed as map with #{map_size(m)} keys")
              {:ok, config}

            other ->
              write_debug(
                "[ConfigLoader] ✗ Parsed but not a map, got: #{inspect(other, limit: 50)}"
              )

              {:error, "Expected map, got #{inspect(other)}"}
          end
        rescue
          e ->
            write_debug("[ConfigLoader] ✗ Exception during parsing: #{inspect(e)}")
            {:error, "Failed to parse config file: #{inspect(e)}"}
        end

      {:error, reason} ->
        write_debug("[ConfigLoader] ✗ Failed to read file: #{inspect(reason)}")
        {:error, reason}
    end
  end
end
